title: Lerntagebuch Marina
author: Marina
description: > # this means to ignore newlines
  Vorlage f√ºr ein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
